### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by grimen** [gravityblast/web-app-theme#1]
It's a waste that this Rails plugin which seems to kickass have no documentation. Would appreciate just a basic example, takes just a few lines. Maybe more people would extend something they know how it's used fully. I just guessed the most basic stuff, but usually don't rely on things without docs. If you give a hint I could write the docs. =)

**Comment by lagsalot** [comment]
I'd contribute to this to.  This project has saved me mountains of time but was in the dark for a couple of hours trying to figure out just how to use it.
