### ISSUE TITLE
Permission denied - public folder

### ISSUE THREAD

**Issue by bolthar** [gravityblast/web-app-theme#27]
When trying to access a deployed application on Heroku, I get the following error:

ActionView::Template::Error (Permission denied - /app/6a14da80-e717-4550-b091-8240c5c50ff4/home/public/stylesheets/.permissions_check.23898592104760.1719.851812)

Works fine when testing the application locally. I've tried to meddle with the permission settings on my public folder, to no avail.

**Comment by gravityblast** [comment]
If you are on heroku you don't have write permission on filesystem, so remove the :cache => true option from the stylesheet_include_tag

**Comment by bolthar** [comment]
Thanks, that solved it

**Comment by taniasupagirl** [comment]
Thanks a lot for this comment! Also remove the :cache => true on the javascript_include_tag. That was my problem.
