### ISSUE TITLE
themed generator errors ...

### ISSUE THREAD

**Issue by lgs** [gravityblast/web-app-theme#4]
Hi, nice work here. Anyway, I get some issues with "themed generator" for a simple home controller:

root@webby2066:/var/rails/bookuntu# script/generate themed home
uninitialized constant Home
root@webby2066:/var/rails/bookuntu# script/generate themed Home
uninitialized constant Home
root@webby2066:/var/rails/bookuntu# script/generate themed HomeController
undefined method `columns' for HomeController:Class
root@webby2066:/var/rails/bookuntu# script/generate themed HomeController --layout=application
undefined method`columns' for HomeController:Class

root@webby2066:/var/rails/bookuntu# grep home config/routes.rb
  map.home '', :controller => 'home', :action => 'index'
  map.connect '/:action/:id', :controller => 'home'
root@webby2066:/var/rails/bookuntu# cat app/controllers/home_controller.rb
class HomeController < ApplicationController
  caches_page :index
end
root@webby2066:/var/rails/bookuntu#

**Comment by lgs** [comment]
... umm, 
better to see here : http://gist.github.com/194123

**Comment by gravityblast** [comment]
Understood. It's because the Themed generator tries to create views for a crud controller, but you don't have a model. I'm going to add an options to create themes for controller without models. Do you need a view with only text like the first block here?
http://pilu.github.com/web-app-theme/

**Comment by lgs** [comment]
Yes, that's it.

**Comment by gravityblast** [comment]
ok, you can now use:

script/generate controller homes
script/generate themed homes --type=text

in your routes.rb:

map.resource :home
