### ISSUE TITLE
Rails 3 compatibility

### ISSUE THREAD

**Issue by marceloverdijk** [gravityblast/web-app-theme#7]
I've installed web-app-theme as plugin using:

> rails plugin install git://github.com/pilu/web-app-theme.git

This worked fine, but installing the theme using:

> rails generate theme 
> gives a: Could not find generator theme.

I guess the plugin needs to be upgraded to be Rails 3 compatible?

**Comment by gravityblast** [comment]
Yes, I didn't try it with rails 3 yet, but we need to upgrade it to be compatible with the new rails version

**Comment by marceloverdijk** [comment]
Perfect!

**Comment by fourfour** [comment]
I second Rails 3. I am lost without web-app-theme :)

**Comment by levifig** [comment]
I'd love this as well… :)

**Comment by gravityblast** [comment]
not yet but it will work with rails 3 soon

**Comment by rurounijones** [comment]
In one of the rails 3 preview articles I seem to remember that you can rip out and replace the templates used by the built-in rails generators. Is that the plan for web-app-theme? being able to generate a web-app-theme scaffold in one command would be fantastic (and make it easier for people to customize their templates)

**Comment by libo** [comment]
Any news pilu :-) I need this for rails 3 !!

**Comment by pedromtavares** [comment]
Although possible to use the themes without the scaffold, it'd be great if you could upgrade it for Rails 3 support, that scaffolding saves some good copying and pasting that would take a few minutes =)

**Comment by technicalpickles** [comment]
Looks like there's at least a few forks that attempt this, at least from recent entries in the network view:
- libo
- lucasefe
- lgs

**Comment by ckgagan** [comment]
include
gem "web-app-theme", :git =>"git://github.com/krishna-shilpakar/web-app-theme.git"
in the gem file and bundle install
Atleast it didn't gave me a "Could not find generator theme." error

**Comment by gravityblast** [comment]
the latest version should work fine with rails 3
